stages:
  - lint
  - build
  - test
  - cleanup
  - push
  - deploy

default:
  tags:
    - docker

lint-yaml:
  stage: lint
  image:
    name: cytopia/yamllint
    entrypoint: ["/bin/ash", "-c"]
  script:
    - yamllint -f colored .

lint-helm:
  stage: lint
  image: alpine/k8s:1.24.15
  script:
    - helm lint .helm

build yelb-ui:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/yelb-ui:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA ./yelb-ui

build yelb-appserver:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/yelb-appserver:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA ./yelb-appserver

test:
  stage: test
  image:
    name: docker/compose:1.29.2
    entrypoint: [""]
  script:
    - docker-compose
        -p "$CI_PROJECT_NAME"_"$CI_COMMIT_SHORT_SHA"
      up
        --abort-on-container-exit
        --exit-code-from test
        --quiet-pull

cleanup:
  stage: cleanup
  image:
    name: docker/compose:1.29.2
    entrypoint: [""]
  script:
    - docker-compose -p "$CI_PROJECT_NAME"_"$CI_COMMIT_SHORT_SHA" down
  when: always

push yelb-ui:
  stage: push
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/yelb-ui:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  only:
    - master

push yelb-appserver:
  stage: push
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/yelb-appserver:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  only:
    - master

deploy:
  stage: deploy
  image: alpine/k8s:1.24.15
  before_script:
    - chmod +x yc
    - ./yc config set token $YC_TOKEN
    - ./yc config set cloud-id $YC_CLOUD_ID
    - ./yc config set folder-id $YC_FOLDER_ID
    - ./yc managed-kubernetes cluster get-credentials k8s-cluster --external
    - export DB_HOST=$(./yc postgresql cluster get k8s-psql-cluster | head -1 | awk '{ print $2 }')
    - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && helm repo update
    - helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
    - kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.9.1/cert-manager.yaml
  script:
    - kubectl get namespace | grep "^$CI_PROJECT_PATH_SLUG " || kubectl create namespace $CI_PROJECT_PATH_SLUG
    - kubectl create secret docker-registry gitlab-ci-token --docker-server $CI_REGISTRY
      --docker-email "s053278@yandex.ru" --docker-username gitlab-ci-token --docker-password $CI_BUILD_TOKEN
      --namespace $CI_PROJECT_PATH_SLUG --dry-run=client -o yaml | kubectl apply -f -
    - helm upgrade --install $CI_PROJECT_PATH_SLUG .helm
        --set ui.image=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/yelb-ui
        --set ui.imageTag=$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
        --set appserver.image=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/yelb-appserver
        --set appserver.imageTag=$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
        --set db.host=c-$DB_HOST.rw.mdb.yandexcloud.net
        --set db.port=6432
        --namespace $CI_PROJECT_PATH_SLUG
        --create-namespace
        --wait
        --timeout 300s
        --atomic
        --debug
  after_script:
    - export BALANCER=$(kubectl get svc | grep LoadBalancer | awk '{ print $4 }')
    - ./yc dns zone add-records --name s053278-ru
        --record "yelb 60 A $BALANCER"
  only:
    - master
