---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-appserver-deployment
spec:
  replicas: {{ .Values.appserver.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-appserver
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-appserver
    spec:
      containers:
        - image: {{ .Values.appserver.image }}:{{ .Values.appserver.imageTag }}
          name: {{ .Chart.Name }}-appserver
          ports:
            - containerPort: 4567
          env:
            - name: "RACK_ENV"
              value: "production"
          resources:
            {{- toYaml .Values.appserver.resources | nindent 12 }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
...
