---
apiVersion: v1
kind: Service
metadata:
  name: yelb-ui
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: yelb-ui
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-appserver
spec:
  ports:
    - port: 4567
      targetPort: 4567
  selector:
    app: yelb-appserver
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-server
  type: ClusterIP
...
