---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-ui
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ .Chart.Name }}-ui
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-appserver
spec:
  ports:
    - port: 4567
      targetPort: 4567
  selector:
    app: {{ .Chart.Name }}-appserver
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-server
  type: ClusterIP
...