---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-ui-deployment
spec:
  replicas: {{ .Values.ui.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-ui
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-ui
    spec:
      containers:
        - image: {{ .Values.ui.image }}:{{ .Values.ui.imageTag }}
          name: {{ .Chart.Name }}-ui
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
...
