---
# Registry
imagePullSecret: gitlab-ci-token

# Frontend
ui:
  replicaCount: 2

  image: mreferre/yelb-ui
  imageTag: "0.7"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  ingress:
    host: yelb.s053278.ru

# Backend
appserver:
  replicaCount: 2

  image: s053278.gitlab.yandexcloud.net:5050/s053278/graduation_work/yelb-appserver
  imageTag: "0.5"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Redis
redis:
  replicaCount: 2

  image: "redis"
  imageTag: "4.0.2"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Database (PostgreSQL)
db:
  host: "yelb-db"
  port: "6432"
  dbname: "k8s-psql-database"
  user: "dbuser"
  password: "P@$$w0rd"
